---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  data_bags_path: /Users/jcalise/Projects/DevOps/chef-repo/data_bags

platforms:
  - name: ubuntu-16.04
    driver:
      box: bento/ubuntu-16.04
  - name: centos-7.2
    driver:
      network:
      - ["forwarded_port", {guest: 8080, host: 80}]
      - ["private_network", {ip: "192.168.33.35"}]

suites:
  - name: managed_server
    run_list:
        - recipe[omc::stage_agent]
        - recipe[omc::install_agent]
        - recipe[omc::monitor_linux]
    attributes:
  - name: bootstrap_server
    run_list:
        - recipe[omc::stage_agent]
    attributes:




